Source/Web/Project.Web/ViewModels/FileSystem/FileSystemNodeViewModel.cs
namespace Project.Web.ViewModels.FileSystem
{
    using System.Collections.Generic;

    public class FileSystemNodeViewModel
    {
        public string id { get; set; }

        public string text { get; set; }

        public string type { get; set; }

        public ICollection<FileSystemNodeViewModel> children { get; set; }
    }
}

Source/Web/Project.Web/ViewModels/FileSystem/FileUploadFormInputModel.cs
namespace Project.Web.ViewModels.FileSystem
{
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public class FileUploadFormInputModel
    {
        [Required]
        public string Directory { get; set; }

        [UIHint("UploadFile")]
        [Required]
        public HttpPostedFileBase FileToUpload { get; set; }
    }
}

Source/Web/Project.Web/Controllers/FileManagerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Project.Web.Controllers
{
    public class FileManagerController : Controller
    {
        // GET: FileManager
        public ActionResult Index()
        {
            return View();
        }
    }
}

Source/Web/Project.Web/Controllers/FileSystemController.cs
namespace Project.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Web;
    using System.Web.Mvc;

    using Project.Common;
    using Project.Common.Extensions;
    using Project.Web.ViewModels.FileSystem;

    public class FileSystemController : Controller
    {
        private const string MainDirectory = GlobalConstants.MainDirectory;

        [HttpPost]
        public ActionResult RenameFolder(string directory, string newName, string oldName)
        {
            if (oldName == newName)
            {
                return this.GridOperationAjaxRefreshData(true, null);
            }

            var path = directory.ReplaceLastOccurrence(oldName, newName);

            try
            {
                //TO DO
                //Check if folder with that name already exists
                Directory.Move(directory, path);
            }
            catch (Exception ex)
            {
                return this.GridOperationAjaxRefreshData(false, ex.Message);
            }

            return this.GridOperationAjaxRefreshData(true, null);
        }

        [HttpPost]
        public ActionResult RenameFile(string directory, string newName, string oldName)
        {
            if (oldName == newName)
            {
                return this.GridOperationAjaxRefreshData(true, null);
            }

            var path = directory.ReplaceLastOccurrence(oldName, newName);

            try
            {
                System.IO.File.Move(directory, path);
            }
            catch (Exception ex)
            {
                return this.GridOperationAjaxRefreshData(false, ex.Message);
            }

            return this.GridOperationAjaxRefreshData(true, null);
        }

        [HttpPost]
        public ActionResult DeleteFolder(string path)
        {
            try
            {
                Directory.Delete(path, true);
            }
            catch (Exception ex)
            {
                return this.GridOperationAjaxRefreshData(false, ex.Message);
            }

            return this.GridOperationAjaxRefreshData(true, null);
        }

        [HttpPost]
        public ActionResult DeleteFile(string path)
        {
            var file = new FileInfo(path);

            try
            {
                file.Delete();
            }
            catch (Exception ex)
            {
                return this.GridOperationAjaxRefreshData(false, ex.Message);
            }

            return this.GridOperationAjaxRefreshData(true, null);
        }

        [HttpGet]
        public ActionResult UploadFile()
        {
            var model = new FileUploadFormInputModel();

            return PartialView("_UploadFileFormPartial", model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult UploadFile(FileUploadFormInputModel model)
        {
            if (model != null && ModelState.IsValid)
            {
                var path = Path.Combine(model.Directory, model.FileToUpload.FileName);

                if (System.IO.File.Exists(path))
                {
                    path = GenerateFileName(model.Directory, model.FileToUpload);
                }

                model.FileToUpload.SaveAs(path);

                return PartialView("_UploadFileFormPartial", new FileUploadFormInputModel());
            }

            return PartialView("_UploadFileFormPartial", model);
        }

        [HttpGet]
        public ActionResult PopulateData()
        {
            var dir = Server.MapPath(MainDirectory);

            var main = new DirectoryInfo(dir);

            var result = new List<FileSystemNodeViewModel>();

            foreach (var item in main.GetDirectories())
            {
                var node = new FileSystemNodeViewModel();
                node.text = item.Name;
                node.id = item.FullName;
                node.type = "root";
                PopulateTree(node.id, node);
                result.Add(node);
            }

            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public void PopulateTree(string dir, FileSystemNodeViewModel node)
        {
            if (node.children == null)
            {
                node.children = new List<FileSystemNodeViewModel>();
            }

            DirectoryInfo directory = new DirectoryInfo(dir);

            foreach (DirectoryInfo subDirectory in directory.GetDirectories())
            {
                FileSystemNodeViewModel childNode = new FileSystemNodeViewModel();
                childNode.id = subDirectory.FullName;
                childNode.text = subDirectory.Name.ToString();
                childNode.type = "root";

                PopulateTree(subDirectory.FullName, childNode);
                node.children.Add(childNode);
            }

            foreach (FileInfo file in directory.GetFiles())
            {
                FileSystemNodeViewModel childNode = new FileSystemNodeViewModel();
                childNode.id = file.FullName;
                childNode.text = file.Name.ToString();
                childNode.type = "file";
                node.children.Add(childNode);
            }
        }

        private JsonResult GridOperationAjaxRefreshData(bool isSuccess, string message)
        {
            return Json(new { success = isSuccess, message = message });
        }

        private string GenerateFileName(string directory, HttpPostedFileBase file)
        {
            string newPath = Path.Combine(directory, file.FileName);
            int count = 1;

            var fileName = Path.GetFileNameWithoutExtension(newPath);
            var fileExtension = Path.GetExtension(newPath);

            while (System.IO.File.Exists(newPath))
            {
                string tempFileName = string.Format("{0} ({1})", fileName, count++);
                newPath = Path.Combine(directory, tempFileName + fileExtension);
            }

            return newPath;
        }
    }
}

Source/Web/Project.Web/Views/FileManager/Index.cshtml
@model Project.Web.ViewModels.FileSystem.FileUploadFormInputModel

@{
    ViewBag.Title = "File Manager";
}
<div class="row">
    <h2>@ViewBag.Title</h2>
</div>

<div class="row">
    <div class="panel panel-default">
        <div class="panel-heading">
            <div class="row">
                <div class="col-md-4 form-inline input-group-sm">
                    <label for="search">Search</label>
                    <input type="text" id="search" class="form-control" />
                </div>
                <div class="col-md-4 col-sm-8 col-xs-8">
                    <button type="button" id="rename-btn" class="btn btn-warning btn-sm"><i class="glyphicon glyphicon-pencil"></i> Rename</button>
                    <button type="button" id="delete-btn" class="btn btn-danger btn-sm"><i class="glyphicon glyphicon-remove"></i> Delete</button>
                </div>
                <div class="col-md-4 col-sm-8 col-xs-8">
                    <div id="update-target">
                        @Html.Partial("_UploadFileFormPartial", Model)
                    </div>
                </div>
            </div>
        </div>
        <div class="panel-body">
            <div id="file-tree">

            </div>
        </div>
    </div>
</div>

@section scripts{
    @Scripts.Render("~/bundles/activate-file-tree")
}

Source/Web/Project.Web/Views/Shared/EditorTemplates/UploadFile.cshtml
@model HttpPostedFileBase
<p class="fileUpload btn btn-default btn-sm">
    <span>Select File</span>
    @Html.UploadFile(model => model, new { @class = "upload", id = "upload-file" })
</p>
<div>
    @Html.ValidationMessageFor(model => model, "", new { @class = "text-danger" })
</div>

Source/Web/Project.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/jquery.unobtrusive-ajax")
    @Scripts.Render("~/bundles/jstree")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink(Project.Common.GlobalConstants.AppName, "Index", "FileManager", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("File Manager", "Index", "FileManager")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>
    @RenderSection("scripts", required: false)
</body>
</html>

Source/Web/Project.Web/Views/Shared/_UploadFileFormPartial.cshtml
@model Project.Web.ViewModels.FileSystem.FileUploadFormInputModel

@using (Html.BeginForm("UploadFile", "FileSystem", new { area = string.Empty }, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
        <div class="row">
            <div class="col-md-3">
                @Html.HiddenFor(model => model.Directory)
                @Html.ValidationMessageFor(model => model.Directory, "", new { @class = "text-danger" })
                @Html.EditorFor(model => model.FileToUpload)
            </div>
            <div class="col-md-2">
                @Html.Submit(new { value = "Upload File", @class = "btn btn-success btn-sm",id="btn-save" })
            </div>
        </div>
}

@Scripts.Render("~/bundles/activate-upload-form")